### ISSUE TITLE
ReferenceError when using Duo as a module

### ISSUE THREAD

**Issue by darsain** [duojs/duo#433] opened 2015-02-09 16:01 UTC
Seeing as CLI works fine, it's weird that using Duo as a module:

```js
var Duo = require('duo');

new Duo(__dirname)
	.entry('var index = require(\'component/indexof\'); console.log(index([0,1], 1));', 'js')
	.run(save);

function save(err, src) {
	if (err) return console.error(err);
	console.log(
		'Generated %d kb big file starting with:\n%s',
		(src.length / 1024).toFixed(2),
		String(src).substr(0, 77) + '...'
	);
}
```

throws this error:

```
ReferenceError: component_compat is not defined
    at Step.component_compat (D:\test\node_modules\duo\node_modules\duo-css-compat\index.js:220:8)
    at Step.<anonymous> (D:\test\node_modules\duo\node_modules\co\index.js:40:16)
    at call (D:\test\node_modules\duo\node_modules\step.js\index.js:87:14)
    at null._onTimeout (D:\test\node_modules\duo\node_modules\step.js\index.js:68:5)
    at Timer.listOnTimeout (timers.js:110:15)
```

Running:

- node 0.12.0
- duo 0.9.6
- Win 8.1

**Comment by darsain** [comment] 2015-03-16 18:48
I've made the report above more concise, removed anything gulp related (as it was not related), and added a minimal code snippet required to replicate this issue.

This really hinders my development workflow as I can't use Duo from gulp, so I run everything manually. Really irritating, so could someone please look at it? I've tried but got spaghetti poisoning :)

**Comment by dominicbarnes** [comment] 2015-03-16 19:12
Ok, looks like we have an issue with the "compiled" script on npm. (looks like it may not have been compiled from ES6 generators into ES5)

Adding the `--harmony` flag fixes this issue for me, does that work for you @darsain ? (I'll work on a proper fix asap)

**Comment by darsain** [comment] 2015-03-16 19:30
Yes, `--harmony` fixes the issue. Thx, gonna switch it on until this gets fixed :)

**Comment by dominicbarnes** [comment] 2015-03-16 19:30
Thanks! Sorry about the delay, but I'll see about merging a fix for this tonight.

**Comment by darsain** [comment] 2015-03-16 19:34
Awesome! :)

**Comment by dominicbarnes** [comment] 2015-03-17 06:40
Blah, the problem is deeper than I thought. Looks like some interaction between code that was compiled by regenerator and ware/wrap-fn is _not_ cooperating. I'm trying to narrow down the exact code-path that causes the problem, but I haven't finished yet.

Thus, I won't be able to fix this tonight as I previously thought. I'll keep working on it though!

**Comment by MatthewMueller** [comment] 2015-03-17 07:02
Chiming in here because I know I've made this mistake in the past... using `fn.name` to call functions does NOT work when the code is minified / compiled and the function names are changed.

**Comment by dominicbarnes** [comment] 2015-03-18 03:37
I was able to find a workaround for this problem. By exporting a hoisted function instead of a function expression, it looks like the compiled code doesn't lose access to the fn by name.

```js
// works
module.exports = compatibility;
function *compatibility() {}

// breaks
module.exports = function *compatibility() {};
```

It's lame to use a workaround like this, but it's another necessary evil I guess.

**Comment by dominicbarnes** [comment] 2015-03-18 03:45
As it turns out, that doesn't work in our case. Other libraries (in particular, `co-parallel`) export/return expressions.

As far as I'm concerned, this is a bug in regenerator itself, so I'll submit an issue upstream.

**Comment by ArmorDarks** [comment] 2015-04-28 20:28
Got similar error during using of `grunt-duojs` task. CLI version works normally

What is really curious that if I call task directly with `grunt duojs` — all works fine. However, if I call it in stack, with `grunt default` for example — I'll receive same error.

What is more interesting, that error happens only if task called after certain other tasks.

For example, this will work:

``` coffee
  grunt.registerTask 'default', [
    'clean'
    'copy:build'
    'duojs' # grunt-duojs
    'nunjucks' # grunt-nunjucks-2-html
    'sprite'
    'webfont'
    'sass'
    'autoprefixer'
    'responsive_images:thumbnails'
    'browserSync'
    'watch'
  ]
```

but this will throw same error:

``` coffee
  grunt.registerTask 'default', [
    'clean'
    'copy:build'
    'nunjucks' # grunt-nunjucks-2-html
    'duojs' # grunt-duojs. Loaded after nunjucks task
    'sprite'
    'webfont'
    'sass'
    'autoprefixer'
    'responsive_images:thumbnails'
    'browserSync'
    'watch'
  ]
```

Why other tasks can cause that error — completely unclear for me, since they all quite isolated.

**Comment by dominicbarnes** [comment] 2015-04-29 23:32
@ArmorDarks your problem should be submitted upstream to the grunt-duojs package.

**Comment by dominicbarnes** [comment] 2015-04-29 23:35
I'm going to close this issue now. If you're getting these errors when requiring `duo`, chances are you've not included the appropriate `--harmony-generators` flag. For anyone who still encounters errors after this point, please create new issue with all relevant details so we can resolve it.

**Closed by dominicbarnes** 2015-04-29 23:35 UTC
