### ISSUE TITLE
bitbucket instead of github?

### ISSUE THREAD

**Issue by btknorr** [duojs/duo#504] opened 2016-03-11 01:21 UTC
Can we use our component.json to pull a dependency from bitbucket instead of github?  If so how do we do this?  

Thanks,

Brian

**Comment by dominicbarnes** [comment] 2016-03-11 03:43
No, this is not supported, and likely never will be.

(closing as a duplicate of both #116 and #248)

**Closed by dominicbarnes** 2016-03-11 03:43 UTC
